In [3]:
import pandas as pd 
import numpy as np
wine = pd.read_csv("winequality.csv") # IMPORT THE DATASET
#print(wine)

attribute = ['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar', 'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density', 'pH', 'sulphates', 'alcohol']
x=wine[attribute]
# print(x)
y=wine.quality
# print(y)
from sklearn.feature_selection import  SelectKBest,f_classif
from numpy import set_printoptions
# feature extraction

test = SelectKBest(score_func=f_classif, k=9) # k value can be changed if required 
fit = test.fit(x,y)

# summarize scores

set_printoptions(precision=10)                  
print(fit.scores_)
features = fit.transform(x)

# summarize selected features 
print(features[5:10,:5])                        


[ 12.8947916122  61.9167386771   3.2457450939  21.2702851751
  42.472251979   19.7236744354  45.2009487919 105.8564338501
  10.103289121    3.64231688   229.7347722751]
[[8.10e+00 2.80e-01 6.90e+00 5.00e-02 3.00e+01]
 [6.20e+00 3.20e-01 7.00e+00 4.50e-02 3.00e+01]
 [7.00e+00 2.70e-01 2.07e+01 4.50e-02 4.50e+01]
 [6.30e+00 3.00e-01 1.60e+00 4.90e-02 1.40e+01]
 [8.10e+00 2.20e-01 1.50e+00 4.40e-02 2.80e+01]]
